# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Defer < Formula
  desc "Zero-autonomy AI. Every decision is yours."
  homepage "https://github.com/defer-ai/cli"
  version "3.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defer-ai/cli/releases/download/v3.5.1/defer_3.5.1_darwin_amd64.tar.gz"
      sha256 "8f2b37070970d26f121fc119aaafa7eba6be421cf028a95d434b998898f1bbf9"

      define_method(:install) do
        bin.install "defer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defer-ai/cli/releases/download/v3.5.1/defer_3.5.1_darwin_arm64.tar.gz"
      sha256 "a03438606477820d6c37c01780de7080c31afa8ea49972abdb09714d5c67d92f"

      define_method(:install) do
        bin.install "defer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defer-ai/cli/releases/download/v3.5.1/defer_3.5.1_linux_amd64.tar.gz"
      sha256 "5126a99935ef0394017d243c15c372f701ca98edc0480cf0a96b74bbbeb7f3cd"
      define_method(:install) do
        bin.install "defer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defer-ai/cli/releases/download/v3.5.1/defer_3.5.1_linux_arm64.tar.gz"
      sha256 "8e7bdc0728fe4c123f4d8d8a7df4050b5e770f43037ef8caec2c7dc688c45b0f"
      define_method(:install) do
        bin.install "defer"
      end
    end
  end

  test do
    system "#{bin}/defer", "--version"
  end
end
