# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Defer < Formula
  desc "Zero-autonomy AI. Every decision is yours."
  homepage "https://github.com/defer-ai/cli"
  version "3.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defer-ai/cli/releases/download/v3.7.2/defer_3.7.2_darwin_amd64.tar.gz"
      sha256 "004ff05606589c2d8753d85ee69187da20ad824f28278a85e0c0d9c2ac9e1fd9"

      define_method(:install) do
        bin.install "defer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defer-ai/cli/releases/download/v3.7.2/defer_3.7.2_darwin_arm64.tar.gz"
      sha256 "f3a68878e07042d8370dae80ac85fc59667891eedf06a95d6b55af99e16f3c0e"

      define_method(:install) do
        bin.install "defer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defer-ai/cli/releases/download/v3.7.2/defer_3.7.2_linux_amd64.tar.gz"
      sha256 "f74a51d43118c3d42a6b6fa720190a81ed008325dc4b53562a18c7e679f8890a"
      define_method(:install) do
        bin.install "defer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defer-ai/cli/releases/download/v3.7.2/defer_3.7.2_linux_arm64.tar.gz"
      sha256 "54abdf80d1d7fb1953f7b8a8458282f297cdf5f53a6a9da1c1386c803ff8a864"
      define_method(:install) do
        bin.install "defer"
      end
    end
  end

  test do
    system "#{bin}/defer", "--version"
  end
end
